In [5]:
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm, Normalize
from matplotlib.ticker import MaxNLocator
import seaborn as sns
from scipy import stats
import re
import nltk
import missingno as msno
from tqdm import tqdm
import json
import statistics
import math

nltk.download("stopwords", quiet=True)
from nltk.corpus import stopwords
from gensim.models import Phrases
from collections import Counter

# enabling Jupyter Lab to include the output of our plots directly in this notebook
%matplotlib inline


# used to avoid blurry output plots in Jupyter Notebooks
%config InLineBackend.figure_format = "retina"

pd.options.mode.chained_assignment = None

In [1]:
for i in range(12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11

In [7]:
infile_df_concept_prob = open('data/df_concept_prob','rb')
df_concept_prob = pickle.load(infile_df_concept_prob)
infile_df_concept_prob.close()

In [8]:
df_concept_prob

,Disk Encryption,Zero-knowledge proof,Authentication protocol,Differential Privacy
0,0,0,0.592982,0
1,0,0,0.6447967,0
2,0,0,0.7154795,0
3,0,0,0.3757747,0
4,0,0,0.4931392,0
...,...,...,...,...
18190,0,0.5383199,0,0
18191,0,0.55506784,0,0
18192,0,0.41947308,0,0
18193,0,0.5999142,0,0
18194,0,0.42650145,0,0

In [9]:
df_concept_prob.describe()

       Disk Encryption  Differential Privacy
count          18195.0               18195.0
mean               0.0                   0.0
std                0.0                   0.0
min                0.0                   0.0
25%                0.0                   0.0
50%                0.0                   0.0
75%                0.0                   0.0
max                0.0                   0.0

In [14]:
df_concept_prob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18195 entries, 0 to 18194
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Disk Encryption          18195 non-null  int64
 1   Zero-knowledge proof     18195 non-null  object
 2   Authentication protocol  18195 non-null  object
 3   Differential Privacy     18195 non-null  int64
dtypes: int64(2), object(2)
memory usage: 568.7+ KB

In [11]:
df_nonnull_AU=df_concept_prob.loc[df_concept_prob['Authentication protocol']!=0].copy()
df_nonnull_AU

,Disk Encryption,Zero-knowledge proof,Authentication protocol,Differential Privacy
0,0,0,0.592982,0
1,0,0,0.6447967,0
2,0,0,0.7154795,0
3,0,0,0.3757747,0
4,0,0,0.4931392,0
...,...,...,...,...
8787,0,0,0.53677106,0
8788,0,0,0.7450855,0
8789,0,0,0.46880797,0
8790,0,0,0.45116332,0
8791,0,0,0.36927044,0

In [12]:
df_nonnull_ZP=df_concept_prob.loc[df_concept_prob['Zero-knowledge proof']!=0].copy()
df_nonnull_ZP

,Disk Encryption,Zero-knowledge proof,Authentication protocol,Differential Privacy
532,0,0.4927018,0.7098925,0
989,0,0.49558318,0.5582277,0
1025,0,0.6822238,0.5705786,0
1370,0,0.88866866,0.6747664,0
1424,0,0.5098354,0.44001147,0
...,...,...,...,...
18190,0,0.5383199,0,0
18191,0,0.55506784,0,0
18192,0,0.41947308,0,0
18193,0,0.5999142,0,0
18194,0,0.42650145,0,0

In [16]:
list_ZP = [float(x) for x in df_concept_prob['Zero-knowledge proof'].tolist()]
list_AP = [float(x) for x in df_concept_prob['Authentication protocol'].tolist()]

In [17]:
sum(list_AP) / len(list_AP)

0.22752570673981884

In [18]:
sum(list_ZP) / len(list_ZP)

0.06103211109810376